version: '3.7'

services:
  #reverse proxy for portal and apps (can be combined with portal for non-development use-case)
  proxy:
    hostname: proxy
    domainname: localhost
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    #*_HOST and PORT defines where the calls should go. portal/app1/app2/.. means the call go into docker-container.
    environment:
      #PORTAL_HOST: 192.168.2.121  #overriden to run the portal as nodejs for faster development
      #PORTAL_PORT: 3000
      PORTAL_HOST: portal
      PORTAL_PORT: 80
      APP1_HOST: app1
      APP1_PORT: 80
      APP2_HOST: app2
      APP2_PORT: 80

  portal:
    build: ./app-root
    image: portal:latest
  app1:
    build: ./app-first
    image: app1:latest
  app2:
    build: ./app-second
    image: app2:latest
